char *getblock(unsigned int atl, int iof);
char *_getline(unsigned int tl);
int backref(int i, char *lp);
int advance(char *lp, char *ep);
int append(int (*f)(void), unsigned int *a);
void blkio(int b, char *buf, int (*iofcn)(int, char*, int));
int cclass(char *set, int c, int af);
void commands(void);
void compile(int eof);
int execute(unsigned int *addr);
void filename(int comm);
int getchr(void);
int getfile(void);
void global(int k);
void init(void);
void newline(void);
void print(void);
void putchr(int ac);
int putline(void);
void _puts(char *sp);
void setwide(void);
void str_reverse(char* s);
void read_file(void);
